# Generated by Django 5.0.3 on 2024-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
