# Generated by Django 4.2.11 on 2024-03-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_task_options_task_edited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
